url: 'https://cyberanode.github.io'
baseurl: 'website'
title: 'CyberAnode'

plugins:
  - jekyll-postcss-v2

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock

collections:
  companies:
    output: true
    permalink: /:collection/:name/
