url: 'https://cyberanode.com'
baseurl: 'website'
title: 'CyberAnode'

description: "Your go-to directory for verified cyber security companies in Australia."

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock

collections:
  companies:
    output: true
    permalink: /:collection/:name/

google_analytics: "G-3VT08M0M4E"
