url: 'https://cyberanode.github.io'
baseurl: 'website'
title: 'CyberAnode'


postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
  - CNAME

collections:
  companies:
    output: true
    permalink: /:collection/:name/

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-3VT08M0M4E"
    anonymize_ip: false # default  
